Email sender
inventorsoft-academy/spring-boot-task pull request #10
Opened 2019-05-22 14:10 UTC by AHGitHubAccount

Home task 4

2019-05-22 18:59 UTC, inventorsoft-academy requested changes

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/DemoApplication.java
> +        String flag = " ";
Please, move this logic into dedicated component

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/Email.java
> +public class Email implements Serializable {
Stateful classes (that should hold data and are mutable) are bad candidates for being spring beans. Sometimes it's worth it but not in this case. You don't need a dependencies and you're creating instances of this class yourself (with new keyword, as any other class). There is no benefit of making this as spring component

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/Email.java
> +        Scanner in=new Scanner(System.in);
This class looks like simple data structure and it shouldn't depend on console. I suggest you to move it from here into component(managed by spring) which is responsible for user interface

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/EmailConfig.java
> +        return new SimpleMailMessage();
Again, the same issue. SimpleMailMessage is stateful, you will have an instance per future email. It doesn't require an external dependencies from application context. There is no reason to make this as spring component.

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/EmailConfig.java
> +    public JavaMailSender getJavaMailSender() {
Good that you found how to configure it yourself, but you can use starter to have it preconfigured for you, just by providing properties inside `application.properties`

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/EmailConfig.java
> +        mailSender.setUsername(Constants.MY_EMAIL);
This shouldn't be a constant. Consider moving it into application properties. If you want to run this application for different sender email you will not able to do so if you go with constants. However, it's easy to do with `application.properties`

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/EmailService.java
> +        for (Email counter:allEmailsList){
Why do you need all of this if `counter.getDeliveryDate().equals(new Date())` should work?

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/EmailService.java
> +            if (counter.getDelieveryDate().compareTo(finallyDate)==0 && !counter.getSended() && !allEmailsList.contains(counter)){
I think you can directly send the message via mail sender here. I don't see a reason for intermediate collection and another scheduled method

2019-05-22 18:59 UTC, inventorsoft-academy commented on src/main/java/com/example/demo/WorkWithJsonFile.java
> +public class WorkWithJsonFile {
Please, consider reading a file during context initialization(remember bean lifecycle?). You can use lifecycle events on boot time to read file into collection and save collection on application shutdown

2019-05-26 21:56 UTC, AHGitHubAccount commented on src/main/java/com/example/demo/EmailService.java
> +            if (/*counter.getDeliveryDate().equals(new Date()) && counter.getSended().equals(false)*/counter.getRecepientName().equals("alexanderpeterburg21@gmail.com") && !counter.getSended() ){
if (counter.getDeliveryDate().equals(new Date()) && counter.getSended().equals(false)) instead of the provided)

2019-10-15 14:44 UTC, closed without merging