Vasyl chorney
inventorsoft-academy/spring-boot-task pull request #14
Opened 2019-10-22 11:30 UTC by VChorney

2019-10-22 11:32 UTC, VChorney commented
I'd like to add validation and little more refactoring

2019-10-27 17:36 UTC, inventorsoft-academy requested changes

2019-10-27 17:36 UTC, inventorsoft-academy commented on src/com/home_work/spring_boot/ui/UIRepresentation.java
> +    ExecutorService executorService = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());
this should be created in separate configuration. do not initialize your dependencies, let spring do it

2019-10-27 17:36 UTC, inventorsoft-academy commented on src/com/home_work/spring_boot/ui/UIRepresentation.java
> +            executorService.shutdown();
UI component shouldn't handle lifecycle of another component.

2019-10-27 17:36 UTC, inventorsoft-academy commented on src/com/home_work/spring_boot/ui/UIRepresentation.java
> +    private void checkMailsForSend() {
Move sending of the emails logic into separate component, it's not responsibility of ui

2020-10-09 11:37 UTC, closed without merging